version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node-api-boilerplate
permissions:
  - object: /home/ubuntu/node-api-boilerplate
    owner: ubuntu
    group: ubuntu
hooks:
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
